<script setup>
import { onMounted, ref } from 'vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import apiClient from '../services/apiClient';
import { createLogger, logException } from '../utils/logger';

const logger = createLogger('AdminUsers');
const users = ref([]); const loading = ref(false); const search = ref(''); const error = ref('');
async function load() { loading.value = true; try { const { data } = await apiClient.get('/admin/users', { params: { search: search.value || undefined } }); users.value = data.data || []; } catch (exception) { error.value = 'دریافت کاربران انجام نشد.'; logger.error('load', 'Admin users failed', logException(exception)); } finally { loading.value = false; } }
async function toggleBan(user) { try { const { data } = await apiClient.patch(`/admin/users/${user.id}/status`, { is_banned: !user.is_banned }); user.is_banned = data.data.is_banned; } catch (exception) { error.value = 'تغییر وضعیت کاربر انجام نشد.'; logger.error('toggleBan', 'User status update failed', logException(exception)); } }
onMounted(load);
</script>

<template><section class="ops-page"><header class="ops-page__header"><div><span>مدیریت سامانه / کاربران</span><h1>مدیریت کاربران</h1><p>وضعیت هویت و دسترسی کاربران را مشاهده و کنترل کنید.</p></div></header><p v-if="error" class="ops-error">{{ error }}</p><div class="ops-toolbar"><label><i class="pi pi-search"></i><input v-model="search" placeholder="جستجو بر اساس نام یا موبایل" @keyup.enter="load" /></label><button type="button" @click="load">جستجو</button></div><div class="ops-table"><DataTable :value="users" :loading="loading" stripedRows responsiveLayout="scroll" emptyMessage="کاربری یافت نشد."><Column field="name" header="کاربر"><template #body="slotProps"><strong>{{ slotProps.data.name || 'بدون نام' }}</strong><small>{{ slotProps.data.mobile }}</small></template></Column><Column field="email" header="ایمیل" /><Column header="نقش"><template #body="slotProps">{{ slotProps.data.roles?.map((role) => role.name).join('، ') || 'کاربر' }}</template></Column><Column header="احراز هویت"><template #body="slotProps"><span :class="slotProps.data.is_verified ? 'status-ok' : 'status-wait'">{{ slotProps.data.is_verified ? 'تایید شده' : 'در انتظار' }}</span></template></Column><Column header="دسترسی"><template #body="slotProps"><button class="ban-button" type="button" @click="toggleBan(slotProps.data)">{{ slotProps.data.is_banned ? 'آزادسازی' : 'مسدودسازی' }}</button></template></Column></DataTable></div></section></template>

<style scoped>
.ops-page { max-width: 1280px; margin: 0 auto; }.ops-page__header { margin-bottom: 25px; }.ops-page__header span { color: #a62626; font-size: 10px; }.ops-page h1 { margin: 7px 0 4px; font-size: 26px; }.ops-page__header p { margin: 0; color: #64748b; font-size: 12px; }.ops-toolbar { display: flex; gap: 8px; margin-bottom: 14px; }.ops-toolbar label { display: flex; width: min(400px, 100%); align-items: center; gap: 8px; padding: 0 12px; border: 1px solid #e2e8f0; border-radius: 7px; background: #fff; color: #94a3b8; }.ops-toolbar input { width: 100%; padding: 10px 0; border: 0; outline: 0; font: inherit; font-size: 11px; }.ops-toolbar button, .ban-button { padding: 9px 13px; border: 1px solid #e2e8f0; border-radius: 7px; background: #fff; color: #475569; cursor: pointer; font: inherit; font-size: 11px; }.ops-table { padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background: #fff; }.ops-table :deep(.p-datatable) { font-size: 11px; }.ops-table :deep(th) { color: #64748b; font-size: 10px; }.ops-table small, .ops-table strong { display: block; }.ops-table small { margin-top: 4px; color: #94a3b8; font-size: 9px; }.status-ok, .status-wait { padding: 4px 7px; border-radius: 9px; font-size: 9px; }.status-ok { background: #dcfce7; color: #166534; }.status-wait { background: #fef3c7; color: #92400e; }.ban-button { color: #a62626; }.ops-error { padding: 10px; background: #fef2f2; color: #b91c1c; font-size: 11px; }
</style>
