<script setup>
import { onMounted, ref } from 'vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import apiClient from '../services/apiClient';
import { createLogger, logException } from '../utils/logger';

const logger = createLogger('PendingAds');
const ads = ref([]); const loading = ref(false); const search = ref(''); const error = ref(''); const selectedAd = ref(null); const rejectionReason = ref(''); const rejecting = ref(false);
const formatMoney = (value) => value ? `${new Intl.NumberFormat('fa-IR').format(value)} میلیون تومان` : 'ثبت نشده';
async function load() { loading.value = true; error.value = ''; try { const { data } = await apiClient.get('/admin/ads/pending', { params: { search: search.value || undefined } }); ads.value = data.data || []; } catch (exception) { error.value = 'دریافت صف آگهی‌ها انجام نشد.'; logger.error('load', 'Pending ads failed', logException(exception)); } finally { loading.value = false; } }
async function approve(ad) { try { await apiClient.post(`/admin/ads/${ad.id}/approve`); ads.value = ads.value.filter((item) => item.id !== ad.id); } catch (exception) { error.value = 'تایید آگهی انجام نشد.'; logger.error('approve', 'Ad approval failed', logException(exception)); } }
async function reject() { if (!selectedAd.value || !rejectionReason.value.trim()) return; try { await apiClient.post(`/admin/ads/${selectedAd.value.id}/reject`, { rejection_reason: rejectionReason.value }); ads.value = ads.value.filter((item) => item.id !== selectedAd.value.id); selectedAd.value = null; rejectionReason.value = ''; rejecting.value = false; } catch (exception) { error.value = 'رد آگهی انجام نشد.'; logger.error('reject', 'Ad rejection failed', logException(exception)); } }
onMounted(load);
</script>

<template><section class="ops-page"><header class="ops-page__header"><div><span>عملیات / آگهی‌ها</span><h1>صف بررسی آگهی‌ها</h1><p>آگهی‌های در انتظار بررسی را ارزیابی و تعیین تکلیف کنید.</p></div><button class="outline-button" type="button" @click="load"><i class="pi pi-refresh"></i>به‌روزرسانی</button></header><p v-if="error" class="ops-error">{{ error }}</p><div class="ops-toolbar"><label><i class="pi pi-search"></i><input v-model="search" placeholder="جستجو در عنوان یا نام کاربر" @keyup.enter="load" /></label><button type="button" @click="load">جستجو</button></div><div class="ops-table"><DataTable :value="ads" :loading="loading" stripedRows responsiveLayout="scroll" emptyMessage="صف بررسی خالی است."><Column field="title" header="آگهی"><template #body="slotProps"><strong>{{ slotProps.data.title }}</strong><small>{{ slotProps.data.user?.name || '-' }}</small></template></Column><Column header="بانک"><template #body="slotProps">{{ slotProps.data.bank?.name || '-' }}</template></Column><Column header="مبلغ وام"><template #body="slotProps">{{ formatMoney(slotProps.data.loan_amount) }}</template></Column><Column field="created_at" header="تاریخ ثبت" /><Column header="عملیات"><template #body="slotProps"><div class="row-actions"><button class="approve" type="button" @click="approve(slotProps.data)">تایید</button><button class="view" type="button" @click="selectedAd = slotProps.data">جزئیات</button><button class="reject" type="button" @click="selectedAd = slotProps.data; rejecting = true">رد</button></div></template></Column></DataTable></div><div v-if="selectedAd" class="ops-modal" role="dialog" aria-modal="true"><div class="ops-modal__box"><button class="ops-modal__close" type="button" @click="selectedAd = null; rejecting = false"><i class="pi pi-times"></i></button><span>جزئیات آگهی</span><h2>{{ selectedAd.title }}</h2><p>{{ selectedAd.description || 'توضیحی ثبت نشده است.' }}</p><div v-if="rejecting"><label for="reject-reason">علت رد آگهی</label><textarea id="reject-reason" v-model="rejectionReason" rows="4" placeholder="علت را برای کاربر بنویسید"></textarea><button class="reject-submit" type="button" :disabled="!rejectionReason.trim()" @click="reject">ثبت رد آگهی</button></div></div></div></section></template>

<style scoped>
.ops-page { max-width: 1280px; margin: 0 auto; }.ops-page__header { display: flex; align-items: flex-end; justify-content: space-between; margin-bottom: 25px; }.ops-page__header span { color: #a62626; font-size: 10px; }.ops-page h1 { margin: 7px 0 4px; font-size: 26px; }.ops-page__header p { margin: 0; color: #64748b; font-size: 12px; }.outline-button, .ops-toolbar > button { padding: 9px 13px; border: 1px solid #e2e8f0; border-radius: 7px; background: #fff; color: #475569; cursor: pointer; font: inherit; font-size: 11px; }.outline-button i { margin-left: 7px; }.ops-toolbar { display: flex; gap: 8px; margin-bottom: 14px; }.ops-toolbar label { display: flex; width: min(400px, 100%); align-items: center; gap: 8px; padding: 0 12px; border: 1px solid #e2e8f0; border-radius: 7px; background: #fff; color: #94a3b8; }.ops-toolbar input { width: 100%; padding: 10px 0; border: 0; outline: 0; font: inherit; font-size: 11px; }.ops-table { padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background: #fff; }.ops-table :deep(.p-datatable) { font-size: 11px; }.ops-table :deep(th) { color: #64748b; font-size: 10px; }.ops-table :deep(td) { color: #475569; }.ops-table small, .ops-table strong { display: block; }.ops-table small { margin-top: 4px; color: #94a3b8; font-size: 9px; }.row-actions { display: flex; gap: 5px; }.row-actions button { padding: 5px 8px; border: 0; border-radius: 5px; cursor: pointer; font: inherit; font-size: 10px; }.approve { background: #dcfce7; color: #166534; }.view { background: #f1f5f9; color: #475569; }.reject { background: #fee2e2; color: #991b1b; }.ops-error { padding: 10px; background: #fef2f2; color: #b91c1c; font-size: 11px; }.ops-modal { position: fixed; inset: 0; z-index: 10; display: grid; place-items: center; background: #02061788; backdrop-filter: blur(4px); }.ops-modal__box { position: relative; width: min(500px, calc(100% - 32px)); padding: 27px; border-radius: 12px; background: #fff; }.ops-modal__box > span { color: #a62626; font-size: 10px; }.ops-modal__box h2 { margin: 7px 0; font-size: 18px; }.ops-modal__box p { color: #64748b; font-size: 12px; line-height: 2; }.ops-modal__close { position: absolute; top: 16px; left: 16px; border: 0; background: transparent; color: #64748b; cursor: pointer; }.ops-modal label { display: block; margin: 15px 0 7px; font-size: 11px; }.ops-modal textarea { box-sizing: border-box; width: 100%; padding: 10px; border: 1px solid #e2e8f0; border-radius: 7px; font: inherit; }.reject-submit { margin-top: 10px; padding: 9px 13px; border: 0; border-radius: 6px; background: #a62626; color: #fff; cursor: pointer; font: inherit; font-size: 11px; }.reject-submit:disabled { opacity: .5; }
@media (max-width: 600px) { .ops-page__header { align-items: flex-start; flex-direction: column; gap: 13px; }.ops-table { padding: 10px; }.row-actions { flex-wrap: wrap; } }
</style>
